//===BEACONS
export const SET_SCANNING_STATE = 'SET_SCANNING_STATE';

export const ADD_EDDYSTONE = 'ADD_EDDYSTONE';
export const DELETE_EDDYSTONE = 'DELETE_EDDYSTONE';
export const UPDATE_EDDYSTONES = 'UPDATE_EDDYSTONES';

//===SEARCH
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_INSTITUTES_REQUEST = 'GET_INSTITUTES_REQUEST';
export const GET_INSTITUTES_SUCCESS = 'GET_INSTITUTES_SUCCESS';
export const GET_INSTITUTES_ERROR = 'GET_INSTITUTES_ERROR';

export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const GET_INSTITUTES_AND_EMPLOYEES_REQUEST =
  'GET_INSTITUTES_AND_EMPLOYEES_REQUEST';
export const GET_INSTITUTES_AND_EMPLOYEES_SUCCESS =
  'GET_INSTITUTES_AND_EMPLOYEES_SUCCESS';
export const GET_INSTITUTES_AND_EMPLOYEES_ERROR =
  'GET_INSTITUTES_AND_EMPLOYEES_ERROR';

export const SET_OBJECT_TO_SHOW = 'SET_OBJECT_TO_SHOW';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
