//===BEACONS
export const SET_SCANNING_STATE = 'SET_SCANNING_STATE';

export const ADD_EDDYSTONE = 'ADD_EDDYSTONE';
export const DELETE_EDDYSTONE = 'DELETE_EDDYSTONE';
export const UPDATE_EDDYSTONES = 'UPDATE_EDDYSTONES';

//===MAP
export const SET_SCALE = 'SET_SCALE';
