import {Dimensions} from 'react-native';
import Colors from '../constants/Colors';
const Window = Dimensions.get('window');
const WIDTH = Window.width;

/**
 * Zawiera parametry położenia budynków kampusu na mapie
 * @example getBuildingCoordinates['a'].x;
 */
export default {
  a: {
    width: WIDTH * 0.063,
    height: WIDTH * 0.259,
    left: WIDTH * 0.639,
    top: WIDTH * 0.494,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  b: {
    width: WIDTH * 0.053,
    height: WIDTH * 0.149,
    left: WIDTH * 0.512,
    top: WIDTH * 0.605,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  c: {
    width: WIDTH * 0.0515,
    height: WIDTH * 0.149,
    left: WIDTH * 0.427,
    top: WIDTH * 0.605,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  d: {
    width: WIDTH * 0.0506,
    height: WIDTH * 0.149,
    left: WIDTH * 0.343,
    top: WIDTH * 0.605,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  e: {
    width: WIDTH * 0.222,
    height: WIDTH * 0.093,
    left: WIDTH * 0.343,
    top: WIDTH * 0.515,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  f: {
    width: WIDTH * 0.113,
    height: WIDTH * 0.052,
    left: WIDTH * 0.081,
    top: WIDTH * 0.5033,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  g: {
    width: WIDTH * 0.095,
    height: WIDTH * 0.185,
    left: WIDTH * 0.095,
    top: WIDTH * 0.225,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    borderWidth: 1,
    position: 'absolute',
  },
  h: {
    width: WIDTH * 0.181,
    height: WIDTH * 0.094,
    left: WIDTH * 0.2505,
    top: WIDTH * 0.221,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  j: {
    width: WIDTH * 0.052,
    height: WIDTH * 0.145,
    left: WIDTH * 0.2505,
    top: WIDTH * 0.3111,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  k: {
    width: WIDTH * 0.0485,
    height: WIDTH * 0.145,
    left: WIDTH * 0.3395,
    top: WIDTH * 0.3111,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
  l: {
    width: WIDTH * 0.09,
    height: WIDTH * 0.073,
    left: WIDTH * 0.866,
    top: WIDTH * 0.544,
    borderWidth: 1,
    borderColor: Colors.primaryDark,
    backgroundColor: Colors.primary,
    opacity: 0.3,
    position: 'absolute',
  },
};
